[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

#[[main]]
#name = "Servicios"
#weight = 300
#identifier = "services"
#url = "/services/"

#[[main]]
#name = "Posts"
#weight = 200
#identifier = "posts"
#url = "/post/"

#[[main]]
#name = "Contact"
#weight = 400
#identifier = "contact"
#url = "/contact/"
